name: Android Pull Request ktlint

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    # android 디렉토리 없앰으로 인한 주석 처리
    # env:
    #   working-directory: ./android

    steps:
      - uses: actions/checkout@v3

      # JDK 설정
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Review Dog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
          github_token: ${{ secrets.github_token }}

      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review

       # Android Build Debug: assembleDebug Release: assembleRelease
      - name: Android Build
        run: ./gradlew clean assembleDebug
        # working-directory: ${{ env.working-directory }}
