name: Android Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    # android 디렉토리 없앰으로 인한 주석 처리
    # env:
    #   working-directory: ./android

    steps:
      # JDK 설정
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          builder-cache: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: SetUp properties
        run: |
          echo "keystore.release.file_path=${{ secrets.KEYSTORE_RELEASE_FILE_PATH }}" > local.properties
          echo "keystore.release.store_password=${{ secrets.KEYSTORE_RELEASE_PW }}" >> local.properties
          echo "keystore.release.key_alias=${{ secrets.KEYSTORE_RELEASE_ALIAS }}" >> local.properties
          echo "keystore.release.key_password=${{ secrets.KEYSTORE_RELEASE_KEY_PW }}" >> local.properties
          
      - name: Review Dog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
          github_token: ${{ secrets.github_token }}
          builder-cache: true

      # test module 제외한 나머지 빌드
      - name: Android Build
        run: |
          ./gradlew build -x :test:build

#      - name: ktlint
#        uses: ScaCap/action-ktlint@master
#        with:
#          github_token: ${{ secrets.github_token }}
#          reporter: github-pr-review
