name: Android Build

on:
  push:
    branches: [ develop, master,feature/github-ci-study ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./android


    steps:
      # Check Current Branches
      - uses: actions/checkout@v2

      # JDK 설정
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          check-latest: true

      # Android SDK 설정
      # - name: SetUp Android SDK
      #  uses: android-actions/setup-android@v2

      # gradlew 권한 획득
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ env.working-directory }}

      # Android Build Debug: assembleDebug Release: assembleRelease
      - name: Generate Release Note
        run: ./gradlew clean assembleDebug
        working-directory: ${{ env.working-directory }}
