name: Build Check

on:
  pull_request:
    branches:
      - master
      - develop
      - preview

jobs:
  build-check:
    runs-on: macos-latest
    # android 디렉토리 없앰으로 인한 주석 처리
    # env:
    #   working-directory: ./android

    steps:
      # JDK 설정
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Checkout
        uses: actions/checkout@v4

      - name: SetUp properties
        run: |
          echo "keystore.release.file_path=${{ secrets.KEYSTORE_RELEASE_FILE_PATH }}" > local.properties
          echo "keystore.release.store_password=${{ secrets.KEYSTORE_RELEASE_PW }}" >> local.properties
          echo "keystore.release.key_alias=${{ secrets.KEYSTORE_RELEASE_ALIAS }}" >> local.properties
          echo "keystore.release.key_password=${{ secrets.KEYSTORE_RELEASE_KEY_PW }}" >> local.properties
          echo "base_url=\"${{ secrets.BASE_URL }}\"" >> local.properties
          echo "auth_type=\"${{ secrets.AUTH_TYPE }}\"" >> local.properties

      # test module 제외한 나머지 빌드
      # ./gradlew build -x :test:build (테스트 모듈을 제외한 모든 빌드 동작해서 시간이 오래걸림)
      - name: Android Build
        run: |
          ./gradlew assembleRelease

      # Fail Message
      # const log = fs.readFileSync('build/reports/tests/test/index.html', 'utf8');
      - name: Post build error messages as PR comment
        if: failure()
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require('fs');
            const log = 'build Error!!'
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Build failed with the following errors:\n\n${log}`
            });

#      - name: ktlint
#        uses: ScaCap/action-ktlint@master
#        with:
#          github_token: ${{ secrets.github_token }}
#          reporter: github-pr-review
