
name: feature build

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        required: true
        description: 'debug or release'
        default: 'debug'
        options:
          - 'debug'
          - 'release'
      release_note:
        type: textarea
        required: false
        description: 'Firebase Release Note'


jobs:
  build:
    runs-on: ubuntu-latest
    # android 디렉토리 없앰으로 인한 주석 처리
    # env:
    #   working-directory: ./android

    steps:
      - uses: actions/checkout@v3

      - name: Select Print
        run: |
          echo ::set-output ${{ inputs.target }}
          echo ::set-output ${{ inputs.release_note }}
