
name: feature build

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        required: true
        description: 'staging or release'
        default: 'staging'
        options:
          - 'staging'
          - 'release'
      release_note:
        type: string
        required: false
        description: 'Firebase Release Note'


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./android
    
    steps:
      - uses: actions/checkout@v3

      - name: Select Print
        run: |
          echo ::set-output ${{ inputs.target }}
          echo ::set-output ${{ inputs.realse_note }}