name: firebase_deploy
on:
  workflow_dispatch:
    inputs:
      build_type:
        type: choice
        required: true
        description: 'debug or release'
        default: 'release'
        options:
          - 'debug'
          - 'release'
      release_note:
        type: string
        required: false
        description: 'Firebase Release Note'

jobs:
    deploy_firebase:
      runs-on: ubuntu-latest
      steps:
        - name: SetUp Environment
          id: appId
          run: |
            if [ "${{ inputs.build_type }}" == "release" ]; then
              echo "::set-output name=val::${{ secrets.FIREBASE_RELEASE_APP_ID }}"
            else
              echo "::set-output name=val::${{ secrets.FIREBASE_DEV_APP_ID }}"
            fi

#        - name: Set Up Node
#          uses: actions/setup-node@v3
#          with:
#            bundler-cache: true

        - name: SetUp JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'adopt'
            bundler-cache: true
        - name: Git Checkout
          uses: actions/checkout@v4

        - name: SetUp properties
          run: |
            echo "keystore.release.file_path=${{ secrets.KEYSTORE_RELEASE_FILE_PATH }}" > local.properties
            echo "keystore.release.store_password=${{ secrets.KEYSTORE_RELEASE_PW }}" >> local.properties
            echo "keystore.release.key_alias=${{ secrets.KEYSTORE_RELEASE_ALIAS }}" >> local.properties
            echo "keystore.release.key_password=${{ secrets.KEYSTORE_RELEASE_KEY_PW }}" >> local.properties
            echo "base_url=\"${{ secrets.BASE_URL }}\"" >> local.properties
            echo "auth_type=\"${{ secrets.AUTH_TYPE }}\"" >> local.properties

        - name: SetUp Ruby
          uses: ruby/setup-ruby@v1
          with:
              ruby-version: '3.0'
              bundler-cache: true
#        - name: SetUp Fastlane
#          uses: maierj/fastlane-action@v3.1.0
#          with:
#              lane: 'firebaseDeploy'
#              options: |
#                {
#                  "build_type": "${{ inputs.build_type }}",
#                  "release_message": "${{ inputs.release_note }}",
#                  "token": "${{ secrets.FIREBASE_TOKEN }}",
#                  "app_id": "${{ steps.appId.outputs.val }}"
#                }
        - name: SetUp App Icon
          id: appIcon
          run: |
            if [ "${{ inputs.build_type }}" == "release" ]; then
              echo "::set-output name=val::${{ :til_icon:  }}"
            else
              echo "::set-output name=val::${{ :til_dev_icon: }}"
            fi
        - name: action-slack
          uses: 8398a7/action-slack@v3
          with:
            status: custom
            fields: workflow,job,commit,repo,ref,author,took
            custom_payload: |
              {
                text: "Firebase AppDistribution",
                attachments: [{
                  fallback: 'fallback',
                  color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                  title: 'Build Type',
                  text: '${{ inputs.build_type }} ',
                  fields: [
                  {
                    title: '${{ steps.appIcon.outputs.val }}',
                    value: 'TIL',
                    short: true
                  },
                  {
                    title: 'reverse',
                    value: 'gnirts esrever'.split('').reverse().join(''),
                    short: true
                  },
                  {
                    title: 'long title1',
                    value: 'long value1',
                    short: false
                  }]
                }]
              }
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_AOS_DEPLOY_WEBHOOK_URL }}
          if: always()

        
        
      
