name: Generate Release Note

on:
  push:
    branches: [ develop, master ]
  # pull_request:
    # branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    # android 디렉토리 없앰으로 인한 주석 처리
    # env:
    #   working-directory: ./android

    steps:
      # Check Current Branches
      - uses: actions/checkout@v4

      # JDK 설정
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      # gradlew 권한 획득
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        # working-directory: ${{ env.working-directory }}

      # 최근에 커밋한 내용으로 릴리즈 노트 작성
      - name: Generate Release Note
        run: ./gradlew generateReleaseNote
        # working-directory: ${{ env.working-directory }}
