name: Libraray Generate Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./android

    steps:
      - uses: actions/checkout@v2

      # JDK 설정
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          check-latest: true
          
     # 최근에 커밋한 내용으로 릴리즈 노트 작성
      - name: Generate Release Note
        run: ./gradlew generateReleaseNote
        working-directory: ${{ env.working-directory }}

      # Dependency 에 버전 및 릴리즈 메시지 가져오기
      - name: Release Version
        id: release
        run: |
          echo ::set-output name=code::$(grep versionCode buildSrc/src/main/java/Dependencies.kt | awk '{print $5}')
          echo ::set-output name=name::$(grep versionName buildSrc/src/main/java/Dependencies.kt | awk '{print $5}')
          echo ::set-output name=title::$(sed -n -e '1,1p' appRelease/release_note.txt)
        working-directory: ${{ env.working-directory }}

      # Tag 명 "" 제거해서 가져오기
      - name: Get Tag Name
        id: get_tag
        run: echo ::set-output name=name::${{steps.release.outputs.name}}

      # Release Message 가져오기
      - name: Get Release Message
        id: get_release
        run: |
          RELEASE_BODY=$(sed -n '2,$p' appRelease/release_note.txt | less)
          RELEASE_BODY="${RELEASE_BODY//'%'/'%25'}"
          RELEASE_BODY="${RELEASE_BODY//$'\n'/'%0A'}"
          RELEASE_BODY="${RELEASE_BODY//$'\r'/'%0D'}"
          echo ::set-output name=val::${RELEASE_BODY}
        working-directory: ${{ env.working-directory }}

      # 릴리즈 생성
      # release_name: 릴리즈 제목
      # tag_name: 버전 이름
      # body: 릴리즈 메시지 내용
      - name: Generate Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{steps.release.outputs.title}}
          tag_name: ${{steps.get_tag.outputs.name}}
          body: |
            ${{steps.get_release.outputs.val}}
          draft: false
          prerelease: false
